fruits = []
fruit = input("Enter Fruit Name: ")
fruits.append(fruit)
fruit = input("Enter Fruit Name: ")
fruits.append(fruit)
fruit = input("Enter Fruit Name: ")
fruits.append(fruit)
fruit = input("Enter Fruit Name: ")
fruits.append(fruit)
fruit = input("Enter Fruit Name: ")
fruits.append(fruit)
fruit = input("Enter Fruit Name: ")
fruits.append(fruit)
fruit = input("Enter Fruit Name: ")
fruits.append(fruit)
fruit = input("Enter Fruit Name: ")
fruits.append(fruit)

print(fruits)